# configs/my_icdar_rec_config.yml
# NOTE: This config assumes you have created a recognition dataset with cropped images.
# You will need an additional script to generate this from the detection ground truth.

Global:
  use_gpu: true
  epoch_num: 100
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec_crnn_mv3_icdar/
  save_epoch_step: 5
  eval_batch_step: [0, 1000]
  cal_metric_during_train: true
  # Download a pretrained recognition model for fine-tuning
  pretrained_model: ./pretrain_models/en_PP-OCRv3_rec_train/best_accuracy
  checkpoints:
  save_inference_dir:
  use_visualdl: false
  infer_img: doc/imgs_words_en/word_10.png
  # Use the multilingual dictionary from PaddleOCR
  character_dict_path: ppocr/utils/dict/en_dict.txt
  character_type: en
  use_space_char: true

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
    warmup_epoch: 5
  regularizer:
    name: L2
    factor: 0.00001

Architecture:
  model_type: rec
  algorithm: CRNN
  Transform:
  Backbone:
    name: MobileNetV3
    scale: 0.5
    model_name: large
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    hidden_size: 48
  Head:
    name: CTCHead
    fc_decay: 0.00001

Loss:
  name: CTCLoss

Train:
  dataset:
    name: SimpleDataSet
    # Root directory containing cropped word images
    data_dir: ./data/rec_data/
    # Path to the recognition training label file
    label_file_list: ["./data/rec_train.txt"]
    transforms:
      # ... (keep default transforms from a base recognizer config)
  loader:
    shuffle: true
    batch_size_per_card: 128
    drop_last: true
    num_workers: 4

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./data/rec_data/
    label_file_list: ["./data/rec_val.txt"]
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 128
    num_workers: 4
